# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 600)
        self.ProductpushButton = QtWidgets.QPushButton(Dialog)
        self.ProductpushButton.setGeometry(QtCore.QRect(50, 500, 131, 31))
        self.ProductpushButton.setObjectName("ProductpushButton")
        self.TrainSetpushButton = QtWidgets.QPushButton(Dialog)
        self.TrainSetpushButton.setGeometry(QtCore.QRect(220, 500, 131, 31))
        self.TrainSetpushButton.setObjectName("TrainSetpushButton")
        self.TrainpushButton = QtWidgets.QPushButton(Dialog)
        self.TrainpushButton.setGeometry(QtCore.QRect(390, 500, 131, 31))
        self.TrainpushButton.setObjectName("TrainpushButton")
        self.TestpushButton = QtWidgets.QPushButton(Dialog)
        self.TestpushButton.setGeometry(QtCore.QRect(560, 500, 131, 31))
        self.TestpushButton.setObjectName("TestpushButton")
        self.AlgorithmSelectcomboBox = QtWidgets.QComboBox(Dialog)
        self.AlgorithmSelectcomboBox.setGeometry(QtCore.QRect(50, 30, 131, 25))
        self.AlgorithmSelectcomboBox.setObjectName("AlgorithmSelectcomboBox")
        self.AlgorithmSelectcomboBox.addItem("")
        self.AlgorithmSelectcomboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(50, 70, 251, 421))
        self.textEdit.setObjectName("textEdit")
        self.SampleModelcomboBox = QtWidgets.QComboBox(Dialog)
        self.SampleModelcomboBox.setGeometry(QtCore.QRect(230, 30, 131, 25))
        self.SampleModelcomboBox.setObjectName("SampleModelcomboBox")
        self.SampleModelcomboBox.addItem("")
        self.SampleModelcomboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(310, 60, 381, 431))
        self.groupBox.setObjectName("groupBox")

        self.retranslateUi(Dialog)
        self.ProductpushButton.clicked.connect(Dialog.ProductSampleData)
        self.TrainSetpushButton.clicked.connect(Dialog.SelectTrainData)
        self.TrainpushButton.clicked.connect(Dialog.TrainModel)
        self.TestpushButton.clicked.connect(Dialog.PartitionSample)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ProductpushButton.setText(_translate("Dialog", "生成样本"))
        self.TrainSetpushButton.setText(_translate("Dialog", "选取训练集"))
        self.TrainpushButton.setText(_translate("Dialog", "训练模型"))
        self.TestpushButton.setText(_translate("Dialog", "数据划分"))
        self.AlgorithmSelectcomboBox.setItemText(0, _translate("Dialog", "PLA算法"))
        self.AlgorithmSelectcomboBox.setItemText(1, _translate("Dialog", "Pocket算法"))
        self.SampleModelcomboBox.setItemText(0, _translate("Dialog", "小方差样本"))
        self.SampleModelcomboBox.setItemText(1, _translate("Dialog", "大方差样本"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
